In [10]:
import http.client
import json
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine , text


load_dotenv()  

api_key = os.getenv("GAS_API")

if not api_key:
    raise ValueError("GAS_API not found in .env")

conn = http.client.HTTPSConnection("api.collectapi.com")

headers = {
    'content-type': "application/json",
    'authorization': f"apikey {api_key}"
    }

conn.request("GET", "/gasPrice/stateUsaPrice?state=WA", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"success":true,"result":{"state":[{"currency":"usd","name":"Washington","lowername":"washington","gasoline":"5.5147","midGrade":"5.7453","premium":"6.0209","diesel":"6.9156"}],"cities":[{"currency":"usd","gasoline":"5.3522","midGrade":"5.6476","premium":"5.9033","diesel":"6.6070","name":"Bellingham","lowername":"bellingham"},{"currency":"usd","gasoline":"5.5907","midGrade":"5.7340","premium":"6.0169","diesel":"6.8403","name":"Bremerton","lowername":"bremerton"},{"currency":"usd","gasoline":"5.4311","midGrade":"5.6760","premium":"5.8612","diesel":"6.9336","name":"Olympia","lowername":"olympia"},{"currency":"usd","gasoline":"5.3576","midGrade":"5.6365","premium":"5.8766","diesel":"7.0173","name":"Richland-Kennewick-Pasco","lowername":"richland-kennewick-pasco"},{"currency":"usd","gasoline":"5.6524","midGrade":"5.8665","premium":"6.1196","diesel":"6.9601","name":"Seattle-Bellevue-Everett","lowername":"seattle-bellevue-everett"},{"currency":"usd","gasoline":"5.3176","midGrade":"5.5811","premium":"5.9036","diesel":"6.9510","name":"Spokane","lowername":"spokane"},{"currency":"usd","gasoline":"5.5290","midGrade":"5.7449","premium":"6.0301","diesel":"6.9612","name":"Tacoma","lowername":"tacoma"},{"currency":"usd","gasoline":"5.3679","midGrade":"5.6728","premium":"5.9761","diesel":"6.8747","name":"Yakima","lowername":"yakima"},{"currency":"usd","gasoline":"5.4109","midGrade":"5.6517","premium":"5.9475","diesel":"6.7718","name":"Vancouver","lowername":"vancouver"},{"currency":"usd","gasoline":"5.1323","midGrade":"5.5490","premium":"5.9240","diesel":"5.9990","name":"Clarkson","lowername":"clarkson"},{"currency":"usd","gasoline":"5.4298","midGrade":"5.5790","premium":"5.9312","diesel":"6.9326","name":"Longview","lowername":"longview"},{"currency":"usd","gasoline":"5.3102","midGrade":"5.4312","premium":"5.7448","diesel":"6.6263","name":"Mount Vernon-Anacortes","lowername":"mount vernon-anacortes"},{"currency":"usd","gasoline":"5.4634","midGrade":"5.6790","premium":"6.1040","diesel":"7.0553","name":"Walla Walla","lowername":"walla walla"},{"currency":"usd","gasoline":"5.4948","midGrade":"5.7306","premium":"5.9772","diesel":"7.0701","name":"Wenatchee","lowername":"wenatchee"}]}}

In [2]:
parsed_data = json.loads(data.decode("utf-8"))
parsed_data

{'success': True,
 'result': {'state': [{'currency': 'usd',
    'name': 'Washington',
    'lowername': 'washington',
    'gasoline': '5.5147',
    'midGrade': '5.7453',
    'premium': '6.0209',
    'diesel': '6.9156'}],
  'cities': [{'currency': 'usd',
    'gasoline': '5.3522',
    'midGrade': '5.6476',
    'premium': '5.9033',
    'diesel': '6.6070',
    'name': 'Bellingham',
    'lowername': 'bellingham'},
   {'currency': 'usd',
    'gasoline': '5.5907',
    'midGrade': '5.7340',
    'premium': '6.0169',
    'diesel': '6.8403',
    'name': 'Bremerton',
    'lowername': 'bremerton'},
   {'currency': 'usd',
    'gasoline': '5.4311',
    'midGrade': '5.6760',
    'premium': '5.8612',
    'diesel': '6.9336',
    'name': 'Olympia',
    'lowername': 'olympia'},
   {'currency': 'usd',
    'gasoline': '5.3576',
    'midGrade': '5.6365',
    'premium': '5.8766',
    'diesel': '7.0173',
    'name': 'Richland-Kennewick-Pasco',
    'lowername': 'richland-kennewick-pasco'},
   {'currency': 'usd',
    'gasoline': '5.6524',
    'midGrade': '5.8665',
    'premium': '6.1196',
    'diesel': '6.9601',
    'name': 'Seattle-Bellevue-Everett',
    'lowername': 'seattle-bellevue-everett'},
   {'currency': 'usd',
    'gasoline': '5.3176',
    'midGrade': '5.5811',
    'premium': '5.9036',
    'diesel': '6.9510',
    'name': 'Spokane',
    'lowername': 'spokane'},
   {'currency': 'usd',
    'gasoline': '5.5290',
    'midGrade': '5.7449',
    'premium': '6.0301',
    'diesel': '6.9612',
    'name': 'Tacoma',
    'lowername': 'tacoma'},
   {'currency': 'usd',
    'gasoline': '5.3679',
    'midGrade': '5.6728',
    'premium': '5.9761',
    'diesel': '6.8747',
    'name': 'Yakima',
    'lowername': 'yakima'},
   {'currency': 'usd',
    'gasoline': '5.4109',
    'midGrade': '5.6517',
    'premium': '5.9475',
    'diesel': '6.7718',
    'name': 'Vancouver',
    'lowername': 'vancouver'},
   {'currency': 'usd',
    'gasoline': '5.1323',
    'midGrade': '5.5490',
    'premium': '5.9240',
    'diesel': '5.9990',
    'name': 'Clarkson',
    'lowername': 'clarkson'},
   {'currency': 'usd',
    'gasoline': '5.4298',
    'midGrade': '5.5790',
    'premium': '5.9312',
    'diesel': '6.9326',
    'name': 'Longview',
    'lowername': 'longview'},
   {'currency': 'usd',
    'gasoline': '5.3102',
    'midGrade': '5.4312',
    'premium': '5.7448',
    'diesel': '6.6263',
    'name': 'Mount Vernon-Anacortes',
    'lowername': 'mount vernon-anacortes'},
   {'currency': 'usd',
    'gasoline': '5.4634',
    'midGrade': '5.6790',
    'premium': '6.1040',
    'diesel': '7.0553',
    'name': 'Walla Walla',
    'lowername': 'walla walla'},
   {'currency': 'usd',
    'gasoline': '5.4948',
    'midGrade': '5.7306',
    'premium': '5.9772',
    'diesel': '7.0701',
    'name': 'Wenatchee',
    'lowername': 'wenatchee'}]}}

In [3]:
type(parsed_data)

dict

In [4]:
cities = parsed_data['result']['cities']
type(cities)

list

In [5]:
cities

[{'currency': 'usd',
  'gasoline': '5.3522',
  'midGrade': '5.6476',
  'premium': '5.9033',
  'diesel': '6.6070',
  'name': 'Bellingham',
  'lowername': 'bellingham'},
 {'currency': 'usd',
  'gasoline': '5.5907',
  'midGrade': '5.7340',
  'premium': '6.0169',
  'diesel': '6.8403',
  'name': 'Bremerton',
  'lowername': 'bremerton'},
 {'currency': 'usd',
  'gasoline': '5.4311',
  'midGrade': '5.6760',
  'premium': '5.8612',
  'diesel': '6.9336',
  'name': 'Olympia',
  'lowername': 'olympia'},
 {'currency': 'usd',
  'gasoline': '5.3576',
  'midGrade': '5.6365',
  'premium': '5.8766',
  'diesel': '7.0173',
  'name': 'Richland-Kennewick-Pasco',
  'lowername': 'richland-kennewick-pasco'},
 {'currency': 'usd',
  'gasoline': '5.6524',
  'midGrade': '5.8665',
  'premium': '6.1196',
  'diesel': '6.9601',
  'name': 'Seattle-Bellevue-Everett',
  'lowername': 'seattle-bellevue-everett'},
 {'currency': 'usd',
  'gasoline': '5.3176',
  'midGrade': '5.5811',
  'premium': '5.9036',
  'diesel': '6.9510',
  'name': 'Spokane',
  'lowername': 'spokane'},
 {'currency': 'usd',
  'gasoline': '5.5290',
  'midGrade': '5.7449',
  'premium': '6.0301',
  'diesel': '6.9612',
  'name': 'Tacoma',
  'lowername': 'tacoma'},
 {'currency': 'usd',
  'gasoline': '5.3679',
  'midGrade': '5.6728',
  'premium': '5.9761',
  'diesel': '6.8747',
  'name': 'Yakima',
  'lowername': 'yakima'},
 {'currency': 'usd',
  'gasoline': '5.4109',
  'midGrade': '5.6517',
  'premium': '5.9475',
  'diesel': '6.7718',
  'name': 'Vancouver',
  'lowername': 'vancouver'},
 {'currency': 'usd',
  'gasoline': '5.1323',
  'midGrade': '5.5490',
  'premium': '5.9240',
  'diesel': '5.9990',
  'name': 'Clarkson',
  'lowername': 'clarkson'},
 {'currency': 'usd',
  'gasoline': '5.4298',
  'midGrade': '5.5790',
  'premium': '5.9312',
  'diesel': '6.9326',
  'name': 'Longview',
  'lowername': 'longview'},
 {'currency': 'usd',
  'gasoline': '5.3102',
  'midGrade': '5.4312',
  'premium': '5.7448',
  'diesel': '6.6263',
  'name': 'Mount Vernon-Anacortes',
  'lowername': 'mount vernon-anacortes'},
 {'currency': 'usd',
  'gasoline': '5.4634',
  'midGrade': '5.6790',
  'premium': '6.1040',
  'diesel': '7.0553',
  'name': 'Walla Walla',
  'lowername': 'walla walla'},
 {'currency': 'usd',
  'gasoline': '5.4948',
  'midGrade': '5.7306',
  'premium': '5.9772',
  'diesel': '7.0701',
  'name': 'Wenatchee',
  'lowername': 'wenatchee'}]

In [6]:
cities_df = pd.DataFrame(cities)
cities_df

,currency,gasoline,midGrade,premium,diesel,name,lowername
0,usd,5.3522,5.6476,5.9033,6.6070,Bellingham,bellingham
1,usd,5.5907,5.7340,6.0169,6.8403,Bremerton,bremerton
2,usd,5.4311,5.6760,5.8612,6.9336,Olympia,olympia
3,usd,5.3576,5.6365,5.8766,7.0173,Richland-Kennewick-Pasco,richland-kennewick-pasco
4,usd,5.6524,5.8665,6.1196,6.9601,Seattle-Bellevue-Everett,seattle-bellevue-everett
5,usd,5.3176,5.5811,5.9036,6.9510,Spokane,spokane
6,usd,5.5290,5.7449,6.0301,6.9612,Tacoma,tacoma
7,usd,5.3679,5.6728,5.9761,6.8747,Yakima,yakima
8,usd,5.4109,5.6517,5.9475,6.7718,Vancouver,vancouver
9,usd,5.1323,5.5490,5.9240,5.9990,Clarkson,clarkson
10,usd,5.4298,5.5790,5.9312,6.9326,Longview,longview
11,usd,5.3102,5.4312,5.7448,6.6263,Mount Vernon-Anacortes,mount vernon-anacortes
12,usd,5.4634,5.6790,6.1040,7.0553,Walla Walla,walla walla
13,usd,5.4948,5.7306,5.9772,7.0701,Wenatchee,wenatchee

In [7]:
cities_df.drop(columns=['lowername'],inplace=True)
cities_df

   currency gasoline midGrade premium  diesel                      name
0       usd   5.3522   5.6476  5.9033  6.6070                Bellingham
1       usd   5.5907   5.7340  6.0169  6.8403                 Bremerton
2       usd   5.4311   5.6760  5.8612  6.9336                   Olympia
3       usd   5.3576   5.6365  5.8766  7.0173  Richland-Kennewick-Pasco
4       usd   5.6524   5.8665  6.1196  6.9601  Seattle-Bellevue-Everett
5       usd   5.3176   5.5811  5.9036  6.9510                   Spokane
6       usd   5.5290   5.7449  6.0301  6.9612                    Tacoma
7       usd   5.3679   5.6728  5.9761  6.8747                    Yakima
8       usd   5.4109   5.6517  5.9475  6.7718                 Vancouver
9       usd   5.1323   5.5490  5.9240  5.9990                  Clarkson
10      usd   5.4298   5.5790  5.9312  6.9326                  Longview
11      usd   5.3102   5.4312  5.7448  6.6263    Mount Vernon-Anacortes
12      usd   5.4634   5.6790  6.1040  7.0553               Walla Walla
13      usd   5.4948   5.7306  5.9772  7.0701                 Wenatchee

In [8]:
cities_df.rename(columns={'name':'cities'}, inplace=True)
cities_df

   currency gasoline midGrade premium  diesel                    cities
0       usd   5.3522   5.6476  5.9033  6.6070                Bellingham
1       usd   5.5907   5.7340  6.0169  6.8403                 Bremerton
2       usd   5.4311   5.6760  5.8612  6.9336                   Olympia
3       usd   5.3576   5.6365  5.8766  7.0173  Richland-Kennewick-Pasco
4       usd   5.6524   5.8665  6.1196  6.9601  Seattle-Bellevue-Everett
5       usd   5.3176   5.5811  5.9036  6.9510                   Spokane
6       usd   5.5290   5.7449  6.0301  6.9612                    Tacoma
7       usd   5.3679   5.6728  5.9761  6.8747                    Yakima
8       usd   5.4109   5.6517  5.9475  6.7718                 Vancouver
9       usd   5.1323   5.5490  5.9240  5.9990                  Clarkson
10      usd   5.4298   5.5790  5.9312  6.9326                  Longview
11      usd   5.3102   5.4312  5.7448  6.6263    Mount Vernon-Anacortes
12      usd   5.4634   5.6790  6.1040  7.0553               Walla Walla
13      usd   5.4948   5.7306  5.9772  7.0701                 Wenatchee

In [9]:
DB_HOST = os.getenv('DB_HOST')
DB_NAME = os.getenv('DB_NAME')
DB_PORT = os.getenv('DB_PORT')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

engine = create_engine(f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

In [12]:
cities_df.to_csv('Data/gas_prices.csv', index=False)

In [ ]:
# checking if our connection is ok
with engine.connect() as conn:
    result = conn.execute(text('select 1;'))
    for i in result:
        print(i)

(1,)

In [12]:
cities_df.to_sql('gas_prices', engine , if_exists='replace', index=False)

14